version: "{build}"

environment:
  matrix:
    - nodejs_version: 4.2.1

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@3.3.10 -g
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm test

cache:
  - node_modules            # local npm modules

matrix:
  fast_finish: true